import React from 'react';
import { LucideIcon } from 'lucide-react';
import { 
  FileImage, 
  FileText, 
  QrCode, 
  ScanLine,
  Paintbrush,
  FileArchive, 
  FileCode, 
  Palette, 
  KeyRound, 
  Timer, 
  Edit3, 
  FileMinus, 
  FilePlus, 
  Volume2, 
  ScanText, 
  Coins, 
  Replace, 
  Crop,
  PenTool,
  Smile,
  Video,
  FileDigit,
  BrainCircuit,
  MessageSquare,
  Type,
  FileHeart,
  Scissors,
  FileVideo,
  FileBadge,
  ImageMinus,
  Eraser,
  Hash,
  Image,
  GitCompare,
  RefreshCw,
  MoveHorizontal,
  Clock,
  Music,
  ClipboardList,
  Lock,
  Info,
  XCircle,
  Keyboard,
  RotateCw,
  RotateCcw,
  Folder,
  VenetianMask,
  ZapOff,
  FileAudio,
  Footprints,
  Minimize2,
  Scale,
  Stethoscope,
  Hash as HashIcon,
  QrCode as QrCodeIcon
} from 'lucide-react';

export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: LucideIcon;
  path: string;
  category: string;
  status?: 'new' | 'popular' | 'available' | 'coming-soon';
}

export const toolsData: Tool[] = [
  // Document Tools
  {
    id: 'image-to-pdf',
    name: 'Image to PDF',
    description: 'Convert images to PDF documents',
    icon: FileImage,
    path: '/image-to-pdf',
    category: 'Documents',
    status: 'popular',
  },
  {
    id: 'pdf-to-image',
    name: 'PDF to Image',
    description: 'Convert PDF pages to images',
    icon: FileText,
    path: '/pdf-to-image',
    category: 'Documents',
    status: 'popular',
  },
  {
    id: 'qr-code-generator',
    name: 'QR Code Generator',
    description: 'Create QR codes for links, text, and more',
    icon: QrCode,
    path: '/qr-code-generator',
    category: 'Documents',
    status: 'popular',
  },
  {
    id: 'qr-code-scanner',
    name: 'QR Code Scanner',
    description: 'Scan and decode QR codes from images or webcam',
    icon: ScanLine,
    path: '/qr-code-scanner',
    category: 'Documents',
    status: 'available',
  },
  {
    id: 'qr-code-styler',
    name: 'QR Code Styler',
    description: 'Create custom styled QR codes with logos and colors',
    icon: Paintbrush,
    path: '/qr-code-styler',
    category: 'Documents',
    status: 'available',
  },
  {
    id: 'jpg-to-png',
    name: 'JPG to PNG',
    description: 'Convert JPG images to PNG format',
    icon: FileImage,
    path: '/jpg-to-png',
    category: 'Documents',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert HTML code to PDF documents',
    icon: FileCode,
    path: '/html-to-pdf',
    category: 'Documents',
  },
  {
    id: 'pdf-merger',
    name: 'PDF Merger',
    description: 'Combine multiple PDF files into one',
    icon: FilePlus,
    path: '/pdf-merger',
    category: 'Documents',
  },
  {
    id: 'pdf-splitter',
    name: 'PDF Splitter',
    description: 'Extract specific pages from PDF files',
    icon: FileMinus,
    path: '/pdf-splitter',
    category: 'Documents',
  },
  {
    id: 'pdf-compressor',
    name: 'PDF Compressor',
    description: 'Reduce PDF file size without losing quality',
    icon: FileArchive,
    path: '/pdf-compressor',
    category: 'Documents',
  },
  {
    id: 'pdf-to-text',
    name: 'PDF to Text',
    description: 'Extract text content from PDF files',
    icon: FileText,
    path: '/pdf-to-text',
    category: 'Documents',
  },
  {
    id: 'pdf-locker',
    name: 'PDF Locker',
    description: 'Secure PDF files with password protection',
    icon: Lock,
    path: '/pdf-locker',
    category: 'Documents',
  },
  {
    id: 'pdf-watermark',
    name: 'PDF Watermark',
    description: 'Add text or image watermarks to PDF files',
    icon: FileBadge,
    path: '/pdf-watermark',
    category: 'Documents',
    status: 'coming-soon',
  },
  
  // Image Tools
  {
    id: 'image-compressor',
    name: 'Image Compressor',
    description: 'Compress and optimize images',
    icon: FileArchive,
    path: '/image-compressor',
    category: 'Images',
  },
  {
    id: 'image-cropper',
    name: 'Image Cropper',
    description: 'Crop and resize images with precision',
    icon: Crop,
    path: '/image-cropper',
    category: 'Images',
  },
  {
    id: 'image-to-qr',
    name: 'Image to QR Code',
    description: 'Convert images into scannable QR codes',
    icon: QrCodeIcon,
    path: '/image-to-qr',
    category: 'Images',
  },
  {
    id: 'image-metadata',
    name: 'Image Metadata Viewer',
    description: 'View and remove hidden EXIF data from images',
    icon: Info,
    path: '/image-metadata',
    category: 'Images',
  },
  {
    id: 'background-remover',
    name: 'Background Remover',
    description: 'Remove backgrounds from images automatically',
    icon: Eraser,
    path: '/background-remover',
    category: 'Images',
    status: 'coming-soon',
  },
  {
    id: 'pixelate-image',
    name: 'Pixelate Image',
    description: 'Blur or pixelate sensitive parts of images',
    icon: ImageMinus,
    path: '/pixelate-image',
    category: 'Images',
    status: 'coming-soon',
  },
  {
    id: 'image-watermark',
    name: 'Image Watermark',
    description: 'Add watermarks to protect your images',
    icon: Image,
    path: '/image-watermark',
    category: 'Images',
    status: 'coming-soon',
  },

  // AI Tools
  {
    id: 'extract-text-from-image',
    name: 'Extract Text from Image',
    description: 'Convert image text to editable content',
    icon: ScanText,
    path: '/extract-text-from-image',
    category: 'AI Tools',
  },
  {
    id: 'ai-image-generator',
    name: 'AI Image Generator',
    description: 'Create images from text descriptions',
    icon: BrainCircuit,
    path: '/ai-image-generator',
    category: 'AI Tools',
    status: 'coming-soon',
  },
  {
    id: 'ai-chatbot',
    name: 'AI Chatbot',
    description: 'Chat with an AI assistant for helpful information',
    icon: MessageSquare,
    path: '/ai-chatbot',
    category: 'AI Tools',
    status: 'coming-soon',
  },
  {
    id: 'ai-text-generator',
    name: 'AI Text Generator',
    description: 'Generate creative and professional text content',
    icon: Type,
    path: '/ai-text-generator',
    category: 'AI Tools',
    status: 'coming-soon',
  },
  {
    id: 'ai-content-summarizer',
    name: 'AI Content Summarizer',
    description: 'Condense long articles into concise summaries',
    icon: FileHeart,
    path: '/ai-content-summarizer',
    category: 'AI Tools',
    status: 'coming-soon',
  },
  
  // Video & Audio Tools
  {
    id: 'video-to-gif',
    name: 'Video to GIF',
    description: 'Convert video clips to GIF animations',
    icon: Video,
    path: '/video-to-gif',
    category: 'Video & Audio',
  },
  {
    id: 'gif-to-video',
    name: 'GIF to Video',
    description: 'Convert GIF animations to video format',
    icon: FileVideo,
    path: '/gif-to-video',
    category: 'Video & Audio',
  },
  {
    id: 'remove-audio-from-video',
    name: 'Remove Audio from Video',
    description: 'Create silent videos by removing audio tracks',
    icon: ZapOff,
    path: '/remove-audio-from-video',
    category: 'Video & Audio',
  },
  {
    id: 'extract-audio-from-video',
    name: 'Extract Audio from Video',
    description: 'Save audio from video files as MP3',
    icon: FileAudio,
    path: '/extract-audio-from-video',
    category: 'Video & Audio',
  },
  {
    id: 'add-audio-to-video',
    name: 'Add Audio to Video',
    description: 'Add or replace audio tracks in video files',
    icon: Volume2,
    path: '/add-audio-to-video',
    category: 'Video & Audio',
  },
  {
    id: 'text-to-speech',
    name: 'Text to Speech',
    description: 'Convert text to spoken voice audio',
    icon: Volume2,
    path: '/text-to-speech',
    category: 'Video & Audio',
  },
  {
    id: 'audio-trimmer',
    name: 'Audio Trimmer',
    description: 'Cut and trim audio files with precision',
    icon: Scissors,
    path: '/audio-trimmer',
    category: 'Video & Audio',
    status: 'coming-soon',
  },
  {
    id: 'video-compressor',
    name: 'Video Compressor',
    description: 'Reduce video file size while maintaining quality',
    icon: FileArchive,
    path: '/video-compressor',
    category: 'Video & Audio',
    status: 'coming-soon',
  },
  
  // Other Tools
  {
    id: 'color-picker',
    name: 'Color Picker',
    description: 'Pick and extract colors from images',
    icon: Palette,
    path: '/color-picker',
    category: 'Other Tools',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Create secure and random passwords',
    icon: KeyRound,
    path: '/password-generator',
    category: 'Other Tools',
  },
  {
    id: 'countdown-timer',
    name: 'Countdown Timer',
    description: 'Set custom countdown timers for events',
    icon: Timer,
    path: '/countdown-timer',
    category: 'Other Tools',
  },
  {
    id: 'text-editor',
    name: 'Text Editor',
    description: 'Edit and format text documents online',
    icon: Edit3,
    path: '/text-editor',
    category: 'Other Tools',
  },
  {
    id: 'currency-converter',
    name: 'Currency Converter',
    description: 'Convert between different currencies',
    icon: Coins,
    path: '/currency-converter',
    category: 'Other Tools',
  },
  {
    id: 'text-replacer',
    name: 'Text Replacer',
    description: 'Find and replace text in documents',
    icon: Replace,
    path: '/text-replacer',
    category: 'Other Tools',
  },
  {
    id: 'text-to-handwriting',
    name: 'Text to Handwriting',
    description: 'Convert text to handwritten notes',
    icon: PenTool,
    path: '/text-to-handwriting',
    category: 'Other Tools',
    status: 'coming-soon',
  },
  {
    id: 'text-to-emoji',
    name: 'Text to Emoji',
    description: 'Convert text into related emoji sequences',
    icon: Smile,
    path: '/text-to-emoji',
    category: 'Other Tools',
  },
  {
    id: 'video-to-qr-code',
    name: 'Video to QR Code',
    description: 'Convert videos to shareable QR codes',
    icon: Video,
    path: '/video-to-qr-code',
    category: 'Other Tools',
    status: 'coming-soon',
  },
  {
    id: 'file-renamer',
    name: 'File Renamer',
    description: 'Batch rename multiple files at once',
    icon: FileDigit,
    path: '/file-renamer',
    category: 'Other Tools',
  },
  {
    id: 'random-text',
    name: 'Random Text Generator',
    description: 'Generate random text and lorem ipsum',
    icon: Hash,
    path: '/random-text',
    category: 'Other Tools',
    status: 'coming-soon',
  },
  {
    id: 'clipboard-manager',
    name: 'Clipboard Manager',
    description: 'Store and organize multiple clipboard items',
    icon: ClipboardList,
    path: '/clipboard-manager',
    category: 'Other Tools',
  },
  {
    id: 'file-metadata',
    name: 'File Metadata Viewer',
    description: 'View hidden information in files',
    icon: Info,
    path: '/file-metadata',
    category: 'Other Tools',
  },
  {
    id: 'zip-extractor',
    name: 'ZIP Extractor',
    description: 'Extract files from ZIP archives',
    icon: FileArchive,
    path: '/zip-extractor',
    category: 'Other Tools',
  },
  {
    id: 'zip-creator',
    name: 'ZIP Creator',
    description: 'Create ZIP archives from multiple files',
    icon: FileArchive,
    path: '/zip-creator',
    category: 'Other Tools',
  },
  {
    id: 'rar-extractor',
    name: 'RAR Extractor',
    description: 'Extract files from RAR archives',
    icon: FileArchive,
    path: '/rar-extractor',
    category: 'Other Tools',
  },
  {
    id: 'word-counter',
    name: 'Word Counter',
    description: 'Count words, characters, and paragraphs',
    icon: HashIcon,
    path: '/word-counter',
    category: 'Other Tools',
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    description: 'Convert between different units of measurement',
    icon: Scale,
    path: '/unit-converter',
    category: 'Other Tools',
  },
];
